name: Crowdin Action without config file

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin action
        uses: VBeytok/crowdin-action@master
        with:
          debug_mode: true
          upload_sources: true
          upload_translations: true
          crowdin_branch_name: l10n_branch_without_config
          dryrun_action: false

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

          download_translations: true
          localization_branch_name: l10n_option_branch_without_config
          create_pull_request: true
          language: 'uk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}