name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@master
      with:
        debug_mode: true
        
        upload_sources: true
        upload_translations: true
        
        crowdin_branch_name: l10n_branch
        identity: 'config/private/.crowdin.yml'
        config: 'config/crowdin.yml'
        dryrun_action: false

        download_translations: true
        localization_branch_name: l10n_option_branch
        create_pull_request: true
        
        pull_request_title: 'New production custom pull request 🔥'
        pull_request_body: 'New production custom pull request body with text and 😊'
        pull_request_labels: 'production, enhancement, good first issue'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
